### ISSUE TITLE
Blue border when the input text gets the focus

### ISSUE THREAD

**Issue by Herve07h22** [js-rcon/react-console-emulator#257]
A blue border appears when the input text gets the focus (Chrome, Safari). That should be configurable with a prop.
  
<img width="798" alt="Capture d’écran 2019-06-27 à 15 32 51" src="https://user-images.githubusercontent.com/37082968/60270650-1e09a680-98f1-11e9-8974-33a141bd1ba3.png">

**Comment by linuswillner** [comment]
That should really not be happening. I notice you mention Safari, I presume you’re using a Mac? I can’t get this to reproduce on Windows at all.

**Comment by Herve07h22** [comment]
Yes, iMac Mojave 10.14.5

That could help : https://stackoverflow.com/questions/3660831/getting-rid-of-the-blue-focus-rectangle-on-input-boxes-in-html-css <https://stackoverflow.com/questions/3660831/getting-rid-of-the-blue-focus-rectangle-on-input-boxes-in-html-css>

Hervé


Camilab.co <https://camilab.co/> - nous fabriquons les logiciels de votre entreprise

**Comment by linuswillner** [comment]
I believe I fixed this issue in c5aa487. Can you go the live demo at https://linuswillner.me/react-console-emulator and see if it works as it should now? 😄

**Comment by Herve07h22** [comment]
The live demo stil doesn't work. The input doesn't have the "outline:none;" property in its style props.
I'm not sure about this multiple style-related props for your input component :

```
className={this.props.inputClassName}
style={styles.input}
css={styles.inputFocus} 
```

I suggest you just add "outline:none" to the input style you define in src/defs/styles/Terminal.js.
Something like this

```
input: {
    border: '0',
    padding: '0 0 0 7px',
    margin: '0',
    flexGrow: '100',
    width: '100%',
    height: '22px',
    background: 'transparent',
    fontSize: '15px',
    color: '#F0BF81',
    fontFamily: 'monospace',
    outline:'none',
  },
```

**Comment by linuswillner** [comment]
I thought to apply a focus-based fix since the StackOverflow article you linked suggested tht. Can you verify the above suggestion works on Mac? It's incredibly difficult to test this when I don't have anything to test it on 😅

**Comment by Herve07h22** [comment]
Yes, the above suggest is OK for Safari & Chrome browsers.

**Comment by linuswillner** [comment]
Thanks for #258, caught this just before bed. Cheers!
