### ISSUE TITLE
When commands function pointer changes, internal `commands` property is not changed

### ISSUE THREAD

**Issue by jvorcak** [js-rcon/react-console-emulator#35]
Thank you for creating this component and open-sourcing it.

While using it I encountered an issue. Because of the implementation of `CDU` where `JSON.stringify` is used, `this.validateCommands()` is not called if the implementation of some function is changed.
https://github.com/js-rcon/react-console-emulator/blob/master/src/components/Terminal.jsx#L230

I think a better compare function (based on comparing pointers) could resolve the issue. I need this because I dynamically change the behaviour of commands based on Redux state.

I might try to create a PR, I'm just very busy right now, so I keep it here if someone wants to take an initiative.

**Comment by linuswillner** [comment]
I was aware of that omission when I created that, but haven’t gotten around to figuring out a better solution. I need to make that check deeper and stop relying on JSON strings - a hack in the first place.

Will take a look at it later.

**Comment by jvorcak** [comment]
@linuswillner thanks for a quick reply. Can't we just `shallow compare` the objects?

**Comment by jvorcak** [comment]
@linuswillner do we need to compare at all? Or wouldn't simple shallow compare be enough? One could still memoize it outside of the component.

**Comment by linuswillner** [comment]
@jvorcak I found it to be a better option to just stringify the two objects and compare them that way, but I do it with a library that preserves the source code to detect even insignificant changes such as changing the function type from regular to arrow. This should catch even the slightest edge cases as only the original function references are compared from here on out.

In any case, your issue should be solved as of 39b84e0. Will push a new version shortly.

**Comment by jvorcak** [comment]
> If you mean simply compare with equality, the validation would always be triggered because `{} === {}` is false in JS. I need to figure out a better way to check if they match. This system exists mainly for performance reasons.

Thanks for a quick fix. I meant `===`, I know that `{} !== {}`, however one can use memorization techniques to truly optimize it. It's important to mention that `JSON.stringify` is quite expensive as well.

**Comment by linuswillner** [comment]
I see. I also considered traversing the objects and converting the function to a string and then comparing the objects through a deep equality library, but ended up just getting the source representations and comparing them.

**Comment by bard** [comment]
Got bit by this. In my case I'm replacing one set of commands with a source-identical set of commands, which however are coming from a different lexical scope. The difference isn't (and cannot be) detected and the terminal keeps calling the old set of commands.

How about something like [react-fast-compare](https://www.npmjs.com/package/react-fast-compare)?

**Comment by linuswillner** [comment]
@bard I wanted to avoid using extra dependencies for this, but it appears this is a legitimate issue. I'll get to fixing it ASAP, thanks for the tip about that comparison tool BTW!

**Comment by linuswillner** [comment]
This is fixed as of abead75.

**Comment by linuswillner** [comment]
Turns out this wasn't fixed after all :laughing: oops. It's actually been fixed now in cee9b4865d53b5d95338dddfe77e55019e7a1ab6.
