### ISSUE TITLE
Provide scrollToBottom method & after command callback

### ISSUE THREAD

**Issue by jvorcak** [js-rcon/react-console-emulator#36]
Hi again,

I'm trying to use this in a real application and I only have limited space to show a console.
I've set `maxHeight` by using `contentClassName` property. However now I want my console to scroll to bottom every time it's needed (after a command is executed).

For this, I'm missing some public method on a component that would
1) Scroll console to a bottom so that I can see my prompt after each command
2) Allows me to specify a callback that will be executed after each command (so that I can call scrollToBottom there), right now I can do it in my custom commands, but I can't do it if the command doesn't exist.

Another option is to have boolean property that will scrollToBottom after command is executed. Maybe it's worth even to have it true by default.

What do you think?

**Comment by linuswillner** [comment]
As for the scroll to bottom thing, I thought I had already implemented that feature but as it seems it got lost somewhere. The terminal is definitely intended to scroll to bottom after input. Your idea of being able to toggle it is cool too, will consider adding it.

The command callback idea is really nifty and something I should have considered initially, it’s passed by me completely. I’ll consider adding that too.

**Comment by linuswillner** [comment]
Pushed my proposed changes in accordance with this request in f2d2525. You can check out the proposed new command callback system and automatic scrolling there.

I believe this is the best of both worlds: Automatic scroll per default that can be disabled if scrolling at a later date is desired. Manual scrolling is also easy to do via the command callback, as all you need to do is to get the root element and set `element.scrollTop = element.scrollHeight`.

**Comment by jvorcak** [comment]
@linuswillner I have a problem trying it on my machine in my project, can you please publish this as alpha to npm? Or you can just merge it, from what I had a look at a code it should work. I'll notify you if it's not sufficient.

**Comment by linuswillner** [comment]
Just published version 1.7.0 to NPM. Feel free to try it out and let me know if any issues arise 😄

**Comment by jvorcak** [comment]
<img width="698" alt="screen shot 2018-11-20 at 22 00 17" src="https://user-images.githubusercontent.com/1083817/48802527-c3331f80-ed0f-11e8-8e12-bb5644a3fbcf.png">

With 1.7.0, I get this error, I thought it was a linking issue of mine when I tried to use it from a forked repo, but now I get it from prod. as well.

**Comment by linuswillner** [comment]
Good grief, why did I not think of that... Yeah of course, it makes total sense now. It’s an issue with the build flow that is only affected by the package. I’ll fix that tomorrow, sorry about this.

I can’t issue a fix at this very moment, but a temporary fix is to obtain the `utils` folder from this repository and place it in a directory one level above `lib/Terminal.js` if you need to make changes quickly. Otherwise you can wait until tomorrow when I can issue a proper fix.

**Comment by linuswillner** [comment]
Moving this conversation to #39.
