### ISSUE TITLE
manualPushToStdout shouldn't be static

### ISSUE THREAD

**Issue by jvorcak** [js-rcon/react-console-emulator#37]
Hi,

Just a small note about `manualPushToStdout`. Wouldn't it be better if it's available as a component function instead of having it static? What if I want to have multiple console instances available?

What do you think? :)

**Comment by linuswillner** [comment]
The manualPushToStdout system is a bit fragile indeed, I didn’t exactly consider it from the perspective of multiple instances as I needed it for JS-RCON quickly.

I’ll think this through and make some revisions to it soon. For now, you can target specific instances by passing element nodes to the function. See the README for more information.

**Comment by linuswillner** [comment]
Update on this issue: I will be releasing a change to this along with many other improvements in the next major version (2.0.0). This will include several breaking changes and may take some time for me to complete.

I have created a project board for v2 at https://github.com/js-rcon/react-console-emulator/projects/1, the state of work going towards this release can be tracked from there.

**Comment by linuswillner** [comment]
I have now completed a solution to this problem for the next major release, which is on the [v2 branch](https://github.com/js-rcon/react-console-emulator/tree/v2). I'll be drafting a pull request for my co-dev to comment on soon which will detail the upcoming changes in plain text.
