### ISSUE TITLE
Require errors

### ISSUE THREAD

**Issue by linuswillner** [js-rcon/react-console-emulator#39]
![](https://user-images.githubusercontent.com/1083817/48802527-c3331f80-ed0f-11e8-8e12-bb5644a3fbcf.png)

With 1.7.0, I get this error, I thought it was a linking issue of mine when I tried to use it from a forked repo, but now I get it from prod. as well.

Edit: I can't re-open @linuswillner

_Originally posted by @jvorcak in https://github.com/js-rcon/react-console-emulator/issues/36#issuecomment-440428023_

**Comment by linuswillner** [comment]
@jvorcak I pushed a fix for the issues outlined here. Please try the new system out and let me know if you encounter any issues.

**Comment by jvorcak** [comment]
<img width="681" alt="screen shot 2018-11-22 at 10 31 24" src="https://user-images.githubusercontent.com/1083817/48893936-c8908700-ee41-11e8-9944-cf45b3aa474e.png">

@linuswillner

**Comment by linuswillner** [comment]
That’s an issue with modern JS syntax. Are you using React without ES6?

**Comment by jvorcak** [comment]
@linuswillner I'm using React with Babel, we also use `...` notation at a lot of places.

**Comment by linuswillner** [comment]
Strange... Transform class properties should be able to do that. Will check.

**Comment by jvorcak** [comment]
Ok we don't transpile a code for `node_modules` and it seems to work fine for all of the libs we're using. I'm not an expert here, but shouldn't this lib also provide a transpiled version?

**Comment by linuswillner** [comment]
I removed the transpilation yesterday to improve the build flow. Guess I’ll have to get Babel back and make it work with the new structure. I’ll do that later today.

**Comment by linuswillner** [comment]
Alright @jvorcak, I think I fixed it for real now. Hope this resolves the issues you had and you can actually get to tinkering with your project 😄

**Comment by jvorcak** [comment]
@linuswillner thanks it works! Thank you very much for your support and **quick** responses! You're the best.

**Comment by linuswillner** [comment]
Awesome! Thanks, I’m glad I got it fixed now so I can actually get back to that other feature request of yours.
