### ISSUE TITLE
Console just expands when a very long string without space is entered

### ISSUE THREAD

**Issue by shantur** [js-rcon/react-console-emulator#413]
<img width="1447" alt="Screenshot 2019-11-25 at 15 28 48" src="https://user-images.githubusercontent.com/586441/69553601-585a9b00-0f98-11ea-815e-3f009070bd12.png">

**Comment by linuswillner** [comment]
This is not a library issue, I just hadn't set a max width on the terminals on the demo page, although I probably should.

See https://github.com/js-rcon/react-console-emulator/blob/master/docs/CONFIG.md#re-styling.
